name: Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        jdk: [graalvm@21.1.0, adopt@1.11]
    name: Test ${{ matrix.os }} -- ${{ matrix.jdk }}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: olafurpg/setup-scala@v12
        with:
          java-version: ${{ matrix.jdk }}
      - name: Set up environment
        run: |
          curl -Lo coursier https://git.io/coursier-cli && chmod +x coursier && ./coursier --help
          java -version
        shell: bash
      - name: Check formatting
        if: matrix.os != 'windows-latest'
        run: |
          ./bin/scalafmt --test
        shell: bash
      - name: Compile and test jsonrpc4s
        run: |
          sbt +test
        shell: bash
